[package]
name = "screen_record_nvenc"
version = "0.1.0"
edition = "2024"
publish = false

[target.'cfg(windows)'.dependencies]
media-pp = { path = "../../../lib", features = ["dxgi-capture"] }
render_common = { path = "../render_common" }

[target.'cfg(target_os = "linux")'.dependencies]
media-pp = { path = "../../../lib", features = [
    "pipewire-screen-capture",
    "cuda",
] }
