[package]
name = "screen_preview_gpu"
version = "0.1.0"
edition = "2024"
publish = false

[target.'cfg(windows)'.dependencies]
media-pp = { path = "../../../lib", features = [
    "dxgi-capture",
    "wgc-capture",
    "d3d11",
] }
render_common = { path = "../render_common" }
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_UI_WindowsAndMessaging",
] }
winit = "0.30"

[target.'cfg(target_os = "linux")'.dependencies]
media-pp = { path = "../../../lib", features = [
    "pipewire-screen-capture",
    "cuda",
] }
render_common = { path = "../render_common" }
winit = "0.30"
