//! Vulkan through FFmpeg: the device FFmpeg decodes, encodes and keeps its
//! Vulkan frames on, which this crate's own Vulkan work runs on as well.

pub(crate) mod bgra_pass;
pub(crate) mod device;
pub(crate) mod frame_access;
pub(crate) mod frames;
pub(crate) mod gpu;

/// FFmpeg's `libavutil/hwcontext_vulkan.h`, generated by `build.rs` from the
/// header of the FFmpeg this is built against — see there for why it is
/// never written out by hand.
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::all,
    clippy::undocumented_unsafe_blocks
)]
pub(crate) mod ffi {
    include!(concat!(env!("OUT_DIR"), "/hwcontext_vulkan.rs"));
}
