[package]
name = "media-pp"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next = "8"
crossbeam-channel = "0.5"
crossbeam-queue = "0.3"
thiserror = "2"
rust-hlog = { path = "../rust-hlog" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["local-time"] }
tracing-appender = "0.2"
windows = { version = "0.62", optional = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
] }
ort = { version = "2.0.0-rc.13", optional = true }
ndarray = { version = "0.17", optional = true }
str0m = { version = "0.21", optional = true, default-features = false, features = [
    "wincrypto",
] }

[features]
d3d12-renderer = ["dep:windows"]
d3d11-renderer = ["dep:windows"]
dxgi-capture = ["dep:windows", "d3d11-renderer"]
rtsp-server = []
ort = ["dep:ort", "dep:ndarray"]
webrtc = ["dep:str0m"]
