[package]
name = "render_common"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
media-pp = { path = "../../../lib", features = ["d3d12-renderer", "d3d11-renderer"] }
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Security",
    "Win32_System_Threading",
] }
